# -*- coding: utf-8 -*-
"""1M1b.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fSXlFW04YQvlLEG23ZFanbjN0e0Z7rl2

# **Project Title

# AI-Powered Fake News Detection System Using Machine Learning**

Librarys
"""

import pandas as pd
import numpy as np
import re
import pickle

from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

"""Data set"""

fake = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/Fake.csv")
true = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/True.csv")

"""Lable"""

fake["label"] = 0
true["label"] = 1

"""Merge datasets"""

data = pd.concat([fake, true], axis=0)

"""Shuffle"""

data = data.sample(frac=1, random_state=42)

"""Text cleaning"""

def clean_text(text):
    text = str(text).lower()
    text = re.sub(r'http\\S+', '', text)
    text = re.sub(r'[^a-zA-Z ]', '', text)
    return text

data["text"] = data["text"].apply(clean_text)

"""Features & Labels"""

X = data["text"]
y = data["label"]

"""TF-IDF"""

vectorizer = TfidfVectorizer(max_features=5000)

X = vectorizer.fit_transform(X)

"""Split"""

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

"""Train Model"""

model = LogisticRegression()

model.fit(X_train, y_train)

"""Accuracy"""

pred = model.predict(X_test)

accuracy = accuracy_score(y_test, pred)

print("Accuracy:", accuracy)

"""Save model"""

pickle.dump(model, open("model.pkl", "wb"))
pickle.dump(vectorizer, open("vectorizer.pkl", "wb"))

print("Model Saved Successfully")